### ISSUE TITLE
Support the latest netbox API (v2.10 as of this writing)

### ISSUE THREAD

**Issue by nzlosh** [StackStorm-Exchange/stackstorm-netbox#18]
There were breaking changes in the netbox api in version ~2.8 which renders this pack incompatible.  From the comments in the code, the last time the actions were generated was for version 2.4 in 2018.

Can this pack be updated to support the latest netbox API?

@lampwins are you still the active maintainer?

**Comment by abhi1693** [comment]
@armab I have updated the pack for v3.1 and raised the PR in https://github.com/StackStorm-Exchange/stackstorm-netbox/pull/20

**Comment by abhi1693** [comment]
@armab This issue can be closed now
