### ISSUE TITLE
Help maintain this pack

### ISSUE THREAD

**Issue by abhi1693** [StackStorm-Exchange/stackstorm-netbox#43]
I'm one of the [core maintainers](https://github.com/netbox-community/netbox/wiki#maintainers) of [NetBox](https://github.com/netbox-community/netbox) and I would like to contribute my time here to fast track the maintainance of this pack.

In the past, I have submitted a few PRs that are still pending to be merged ie #30 and #31

I'll also submit PRs to add support for NetBox v3.6 and v3.7 today. I hope to someone from the stackstorm team can help roll out releases for this pack soon.

**Comment by nzlosh** [comment]
Hello @abhi1693

Thank you for offering to help maintain the netbox pack, it is most appreciated.  I've created a PR to add you as a code owner.  Once reviewed and approved by other StackStorm maintainers, you will be included as a maintainer for the netbox pack.

**Comment by abhi1693** [comment]
@nzlosh I have submitted all PRs to support any missing netbox version and have commented on the PR which one to be merged first. I'm hoping to have mulitple releases so that anyone on a particular release can benefit from these updates. With NetBox any API changes are only made in either major or minor release.

**Comment by nzlosh** [comment]
@abhi1693 The MR has been approved and I've sent you an invitation to join this repo.
